{% set name = "openai" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3cd5b10399eb97e498f97a7bf88ffbd101fa44fb35bfe7c4885f87c1c672f892
  patches:
    - 001-remove-fancy-pypi-readme.patch

build:
  number: 0
  entry_points:
    - openai=openai.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # Minimum required version is 3.7.1, and s390x does not have pandas-stubs
  skip: True # [py<37 or s390x]

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - anyio <5,>=3.5.0
    - distro <2,>=1.7.0
    - httpx <1,>=0.23.0
    - pydantic <3,>=1.9.0
    - sniffio
    - tqdm >4
    - typing-extensions <5,>=4.7
    - cached-property  # [py<38]
  run_constrained:
    # The following are required for the optional things.
    - numpy >=1
    - pandas >=1.2.3
    - pandas-stubs >=1.1.0.11

test:
  imports:
    - openai
    - openai.version
  commands:
    - openai api -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openai/openai-python
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/openai/openai-python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
