{% set name = "openai" %}
{% set version = "3.17.0" %}

# respx does not exist in main and needed by conftest.py
# Unable to configure tests
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28910914e6ffaf622f1bbf5dfe02e221cc2b929e492dd30d06b6826939dedf92

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling ==1.27.0
    - hatch-fancy-pypi-readme
  run:
    - python
    - httpx >=0.23.0,<1
    - pydantic >=1.10.13,<3,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*
    - typing-extensions >=4.14,<5
    - anyio >=4.10.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - tqdm >4
    - jiter >=0.16.0,<1
    - httpx2 >=2.12.0,<3
    - typing_extensions >=4.14,<5
  run_constrained:
    # The following are required for the optional things.
    # Extra: aiohttp
    # - aiohttp >=3.14.1
    - httpx_aiohttp >=0.1.9
    # extra: datalib
    # - numpy >=1
    - pandas >=1.2.3
    - pandas-stubs >=1.1.0.11
    # extra: realtime
    - websockets >=13,<16
    # extra: voice_helpers
    - sounddevice >=0.5.1
    # - numpy >=2.0.2
    - aiohttp >=3.14.3
    - botocore >=1.40.0,<2
    - urllib3 >=2.7.0,<3
    - numpy >=2.0.2
    - python-sounddevice >=0.5.1

test:
  source_files:
    - tests
    - pyproject.toml
    - README.md
  imports:
    - openai
    - openai.version
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/openai/openai-python
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/openai/openai-python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
