{% set name = "openai" %}
{% set version = "1.109.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d173ed8dbca665892a6db099b4a2dfac624f94d20a93f46eb0b56aae940ed869

build:
  number: 0
  entry_points:
    - openai=openai.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.26.3
    - hatch-fancy-pypi-readme
  run:
    - python
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.11,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - tqdm >4
    - jiter >=0.4.0,<1
  run_constrained:
    # The following are required for the optional things.
    # Extra: aiohttp
    - httpx_aiohttp >=0.1.8
    # extra: datalib
    - pandas >=1.2.3
    - pandas-stubs >=1.1.0.11
    # extra: realtime
    - websockets >=13,<16
    # extra: voice_helpers
    - sounddevice >=0.5.1
    # - numpy >=2.0.2

# respx =* * does not exist
{% set ignore_tests = " --ignore=tests/test_client.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/lib/test_pydantic.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/lib/test_azure.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/lib/responses/test_responses.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/lib/chat/test_completions.py" %}

# inline-snapshot =* * does not exist
{% set ignore_tests = ignore_tests + " --ignore=tests/lib/chat/test_completions_streaming.py" %}

# httpcore.ConnectError: [Errno 61] Connection refused
# https://github.com/openai/openai-python/blob/v1.60.1/CONTRIBUTING.md#running-tests
# Won`t setup and run mocked openai server with prism.
{% set ignore_tests = ignore_tests + " --ignore=tests/api_resources" %}

# AttributeError: 'async_generator' object has no attribute 'audio'
# AttributeError: 'async_generator' object has no attribute 'beta'
# AttributeError: 'async_generator' object has no attribute '_make_sse_decoder'
# Fixed in pytest-asyncio 0.24.0 (tested with conda-forge channel)
# In main channel latest is ( pytest-asyncio 0.23.8 pkgs/main )
# Update 5/7/2025
# pytest-asyncio>=0.24.0 is available, but tests still fail for same reason
{% set tests_to_skip = "test_response_basemodel_request_id" %}

test:
  source_files:
    - tests
    - pyproject.toml
    - README.md
  imports:
    - openai
    - openai.version
  commands:
    - openai api -h
    - pip check
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})"
  requires:
    - pip
    - pytest
    - pytest-asyncio >=0.24.0
    - pytest-xdist
    - dirty-equals
    - rich >=13.7.1

about:
  home: https://github.com/openai/openai-python
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/openai/openai-python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
