{% set name = "openai" %}
{% set version = "3.26.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73b470c09cf2171dce930e36af01c6632241adda0120ad84302ad229f9130a5a

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling >=1.27.0
  run:
    - python
    - httpx2 >=2.12.0,<3
    - pydantic >=1.10.13,<3,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*
    - typing-extensions >=4.14,<5
    - anyio >=4.10.0,<5
    - sniffio
    - jiter >=0.16.0,<1
  run_constrained:
    # Extra aiohttp
    - aiohttp >=3.14.3
    # Extra realtime
    - websockets >=13,<16
    # Extra datalib
    - pandas >=1.2.3
    # numpy >=1
    # Extra voice_helpers
    - sounddevice >=0.5.1
    - numpy >=2.0.2
    # Extra bedrock
    - botocore >=1.40.0,<2
    - urllib3 >=2.7.0,<3

{% set deselect_tests = "" %}
# AssertionError: assert 0 == 1
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::TestAsyncOpenAI::test_proxy_environment_variables" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::TestOpenAI::test_proxy_environment_variables" %}       # [win]

test:
  source_files:
    - tests
    - scripts
    - pyproject.toml
    - README.md
  imports:
    - openai
    - openai.version
  commands:
    - pip check
    - pytest -vv tests/test_client.py tests/test_streaming.py tests/lib/test_pydantic.py {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-asyncio
    - rich
    - aiohttp
    - urllib3
    - websockets
    - inline-snapshot

about:
  home: https://github.com/openai/openai-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  doc_url: https://github.com/openai/openai-python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim